### ISSUE TITLE
Potential response time issue

### ISSUE THREAD

**Issue by JacobAMason** [henryjr1/DelterAirlinesTeam3#5]
We are having problems with searches taking a very long time to complete on `/Flight-Search` and even on the generic `/flights`. It seems that any request that would return data is very slow.

**Comment by aqd14** [comment]
We understand your concerns. We recently done some database refactoring so it might cause this unexpected issue. We will try to check the commit and fix the problem.

**Comment by aqd14** [comment]
Issue got fixed. Please help us check. Sorry for the inconvenience

**Comment by JacobAMason** [comment]
I think this got fixed

**Comment by JacobAMason** [comment]
After the fixes in #6, this seems to be an issue again

**Comment by aqd14** [comment]
What APIs did you use? I can get flights, purchase history and order new ticket.

**Comment by JacobAMason** [comment]
I'm using the new endpoints at http://35.193.165.105/api/v1.2.1/

**Comment by aqd14** [comment]
Not sure what happened on your side but all members in our team can access all endpoints within a reasonable response time. I have checked and couldn't found any issue.

**Comment by JacobAMason** [comment]
I'm not sure either. It could be a google cloud thing.
