### ISSUE TITLE
purchase endpoint missing

### ISSUE THREAD

**Issue by JacobAMason** [henryjr1/DelterAirlinesTeam3#6]
I'm getting a 404 for `/purchase/order` specifically at http://35.193.165.105/api/v1.1/purchase/order
I realize also that the API is on version 1.2.1 but the url is still `v1.1`

**Comment by aqd14** [comment]
Sorry, we missed the 's' in the APIs. We just updated SwggerHub and URL. You will be able to perform POST request at http://35.193.165.105/api/v1.2.1/purchases/order like this

http://35.193.165.105/api/v1.2.1/purchases/order?ticketID=5&name=Do%20Quoc%20Anh&dob=1994-11-05&email=doquocanh@gmail.com&address=Butler%20Hall

**Comment by JacobAMason** [comment]
I'll test it shortly. Please mark your APIs as published

**Comment by JacobAMason** [comment]
Endpoint is there, but requests are timing out again as in #5

**Comment by JacobAMason** [comment]
`http://35.193.165.105/api/v1.2.1/purchases/order?ticketId=59&?username=hello&user=hello` This is giving us 500s. Are we supposed to register a user first?

**Comment by aqd14** [comment]
Hey Jacob, could you try with this format: http://35.193.165.105/api/v1.2.1/purchases/order?ticketID=5&name=Do%20Quoc%20Anh&dob=1994-11-05&email=doquocanh@gmail.com&address=Butler%20Hall

We have been having issue with Swagger that we can't edit it to reflect what we actually have in our code. So, the current purchases/oder endpoint  is outdated. Sorry for this inconvenience.

**Comment by JacobAMason** [comment]
We rely on swagger to generate our api clients. We only communicate with your api through your api spec. If you are having issues with swagerhub, we can still generate from the yaml file, but we must have something.

**Comment by aqd14** [comment]
We updated APIs on Swagger but decided to keep the version in URL (1.2.1).

**Comment by JacobAMason** [comment]
I'm not sure what format the dob should be, but this isn't a field we need to use. We don't store any email, address, or dob. And we only store a username that we will use in place of the name.

**Comment by aqd14** [comment]
Yes, I see, we tried to have more information to make our front-end display looks more realistic. So please make the correct API call and retrieve whatever you want. The dob format is YYYY-mm-dd just as in comment above

**Comment by JacobAMason** [comment]
looks good
